#! /bin/bash
# ######################################################
#
# Return albums sorted by amount of items.
# 
# Number of displayed albums is defined by user as 
# a script parameter which default value is 10.
#
# If -h exists then add header to script result
# 
# Example: highest filename [howmany] [-h]
#
########################################################



#if [ -n "2" ]; then
#  sort -nr $1 | head -$2
#else
#  sort -nr $1
#fi

eval sort -nr \$1 ${2:+"| head -\$2"}
