#! /bin/bash

if [ $# -gt 3 ]; then
  printf "To many arguments. Usage: mfmcp file dest1 dest2\n"  
  exit
fi

file=$1

if [ $2 = $3 ]; then
  shift
fi  
# because in for loop we want to have params 2 and 3
shift

for dest in $@; do
  # & - run in background to parallelize processes
  cp $file $dest &
done
wait # first finised wait for second process
